/** @format */

export default {
  //root main
  AUTH_CONTAINER: 'AUTH_CONTAINER',
  DRAWER_CONTAINER: 'DRAWER_CONTAINER',
  BOTTOM_CONTAINER: 'BOTTOM_CONTAINER',
  COMMON_CONTAINER: 'COMMON_CONTAINER',

  //auth
  LOGIN_SCREEN: 'LOGIN_SCREEN',
  REGISTER_SCREEN: 'REGISTER_SCREEN',

  //bottom
  HOME_SCREEN: 'HOME_SCREEN',
  SHOP_SCREEN: 'SHOP_SCREEN',
  PLAN_SCREEN: 'PLAN_SCREEN',
  PROFILE_SCREEN: 'PROFILE_SCREEN',

  //drawer
  SETTING_SCREEN: 'SETTING_SCREEN',
  SUPPORT_SCREEN: 'SUPPORT_SCREEN',
  PROMOTION_SCREEN: 'PROMOTION_SCREEN',
  TERMS_POLICY_SCREEN: 'TERMS_POLICY_SCREEN',
  REFER_FRIEND_SCREEN: 'REFER_FRIEND_SCREEN',
  LOCATION_SAVED_SCREEN: 'LOCATION_SAVED_SCREEN',
  ORDER_HISTORY_SCREEN: 'ORDER_HISTORY_SCREEN',
  ACCOUNT_INTRO_SCREEN: 'ACCOUNT_INTRO_SCREEN',
  CHANGE_PASSWORD_SCREEN: 'CHANGE_PASSWORD_SCREEN',
  REVENUE_STATISTICS_SCREEN: 'REVENUE_STATISTICS_SCREEN',
  PRODUCT_MANAGEMENT_SCREEN: 'PRODUCT_MANAGEMENT_SCREEN',

  //common
  SCAN_SCREEN: 'SCAN_SCREEN',
  CART_SCREEN: 'CART_SCREEN',
  PRODUCT_DETAIL_SCREEN: 'PRODUCT_DETAIL_SCREEN',
  STORE_CHECKIN_HISTORY_SCREEN: 'STORE_CHECKIN_HISTORY_SCREEN',
  // common > location
  LOCATION_FORM_SCREEN: 'LOCATION_FORM_SCREEN',

};
