export interface BlockProps {
  flex?: string | number;
  flexGrow?: string | number;
  flexShrink?: string | number;
  row?: boolean;
  column?: boolean;
  spaceBetween?: boolean;
  spaceAround?: boolean;
  spaceEvenly?: boolean;
  wrap?: boolean;
  rowCenter?: boolean;
  columnCenter?: boolean;
  alignStart?: boolean;
  alignCenter?: boolean;
  alignEnd?: boolean;
  justifyStart?: boolean;
  justifyCenter?: boolean;
  justifyEnd?: boolean;
  overflow?: string;
  alignSelfStretch?: boolean;
  alignSelfStart?: boolean;
  alignSelfEnd?: boolean;
  alignSelfCenter?: boolean;
  zIndex?: string | number;
  padding?: string | number;
  margin?: string | number;
  paddingTop?: string | number;
  paddingRight?: string | number;
  paddingBottom?: string | number;
  paddingLeft?: string | number;
  marginTop?: string | number;
  marginRight?: string | number;
  marginBottom?: string | number;
  marginLeft?: string | number;
  paddingVertical?: string | number;
  paddingHorizontal?: string | number;
  marginVertical?: string | number;
  marginHorizontal?: string | number;
  radius?: string | number;
  borderTopRadius?: string | number;
  borderBottomRadius?: string | number;
  borderLeftRadius?: string | number;
  borderRightRadius?: string | number;
  borderTopLeftRadius?: string | number;
  borderTopRightRadius?: string | number;
  borderBottomLeftRadius?: string | number;
  borderBottomRightRadius?: string | number;
  borderWidth?: string | number;
  borderTopWidth?: string | number;
  borderRightWidth?: string | number;
  borderBottomWidth?: string | number;
  borderLeftWidth?: string | number;
  borderDashed?: boolean;
  borderDotted?: boolean;
  translateY?: string | number;
  safePaddingAreaTop?: boolean;
  safeMarginAreaTop?: boolean;
  safePaddingAreaBottom?: boolean;
  safeMarginAreaBottom?: boolean;
  width?: string | number;
  height?: string | number;
  maxWidth?: string | number;
  maxHeight?: string | number;
  square?: boolean;
  round?: boolean;
  relative?: boolean;
  absolute?: boolean;
  absoluteFillObject?: boolean;
  top?: string | number;
  left?: string | number;
  right?: string | number;
  bottom?: string | number;
  backgroundColor?: string;
  borderColor?: string;
  color?: string;
  opacity?: string | number;
  shadow1?: boolean;
  shadow2?: boolean;
  shadow3?: boolean;
  shadow4?: boolean;
  shadow5?: boolean;
  onLayout?: () => void;
  style?: object;
  children?: React.ReactNode;
}
